---

plugins:
  - jest
  - babel

env:
  node: true
  jest: true
  browser: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  # - 'plugin:jest/recommended'

rules:
  no-console: 0
  import/extensions: 0
  jest/no-disabled-tests: warn
  jest/no-focused-tests: error
  jest/no-identical-title: error
  jest/prefer-to-have-length: warn
  jest/valid-expect: error
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]